ROS 2 Jazzyへの対応
rt-net/raspimouse_slam_navigation_ros2 pull request #13
Opened 2024-11-27 02:35 UTC by KuraZuzu

# What does this implement/fix?

ROS 2 Jazzyに対応します。

# Does this close any currently open issues?

しません

# How has this been tested?

## 動作環境

- Raspberry Pi Mouse V3
  - Raspberry Pi 4B (4GB) 
  - Ubuntu Server 24.04 (6.8.0-1014-raspi)
  - ROS 2 Jazzy Base
  - LiDAR: urg
- Remote PC
  - Ubuntu Desktop 24.04 (6.8.0-49-generic)
  - ROS 2 Jazzy Desktop
  - Gazebo Harmonic v8.6.0

## 動作手順

[README.md](https://github.com/rt-net/raspimouse_slam_navigation_ros2/blob/feature/support-jazzy/README.md)の手順に沿って動作を確認しました。

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-11-27 05:52 UTC, YusukeKato requested changes
レビューコメントの確認をお願いいたします。

2024-11-27 05:52 UTC, YusukeKato commented on README.md
> +ros2 launch raspimouse_slam pc_slam.launch.py use_sim_time:=False
同じく`use_sim_time`のパラメータがなさそうな箇所。

2024-11-27 05:52 UTC, YusukeKato commented on README.md
> +ros2 launch raspimouse_slam pc_slam.launch.py use_sim_time:=False
pc_slam.laucnh.pyを読んでみるとuse_sim_timeのパラメータはなさそうな気がします。

2024-11-27 05:52 UTC, YusukeKato commented on README.md
> +ros2 launch raspimouse_navigation pc_navigation.launch.py use_sim_time:=False map:=/path/to/MAP_FILE.yaml
実機を動かすのがメインなので、`use_sim_time`はデフォルトでは`True`でお願いします。
つまり、実機動作時は`use_sim_time`の設定はしなくて大丈夫な状態にしたいです。

2024-11-27 05:52 UTC, YusukeKato commented on raspimouse_navigation/launch/pc_navigation.launch.py
> +    use_sim_time = LaunchConfiguration('use_sim_time', default='True')
`use_sim_time`はデフォルトでは`False`でお願いします。

2024-11-27 08:58 UTC, YusukeKato requested changes
追加でコメントします。

2024-11-27 08:58 UTC, YusukeKato commented on README.md
> +ros2 launch raspimouse_navigation pc_navigation.launch.py use_sim_time:=False map:=/path/to/MAP_FILE.yaml
コピペするだけで動かせるようにマップファイルの指定方法を下記のように修正お願いします。
```suggestion
ros2 launch raspimouse_navigation pc_navigation.launch.py use_sim_time:=False map:=$HOME/MAP_NAME.yaml
```

2024-11-27 08:59 UTC, YusukeKato commented
実機でSLAMとNavigationの動作確認できました！
コメントの確認&修正をお願いいたします。

2024-11-28 02:09 UTC, KuraZuzu commented on README.md
> +ros2 launch raspimouse_slam pc_slam.launch.py use_sim_time:=False
削除しました。

2024-11-28 02:09 UTC, KuraZuzu commented on README.md
> +ros2 launch raspimouse_slam pc_slam.launch.py use_sim_time:=False
削除しました。

2024-11-28 02:09 UTC, KuraZuzu commented on README.md
> +ros2 launch raspimouse_navigation pc_navigation.launch.py use_sim_time:=False map:=/path/to/MAP_FILE.yaml
削除しました。

2024-11-28 02:09 UTC, KuraZuzu commented on raspimouse_navigation/launch/pc_navigation.launch.py
> +    use_sim_time = LaunchConfiguration('use_sim_time', default='True')
Falseにしました。

2024-11-28 02:10 UTC, KuraZuzu commented on README.md
> +ros2 launch raspimouse_navigation pc_navigation.launch.py use_sim_time:=False map:=/path/to/MAP_FILE.yaml
パスを修正しました。

2024-11-28 02:26 UTC, KuraZuzu commented on raspimouse_navigation/launch/pc_navigation.launch.py
> +    use_sim_time = LaunchConfiguration('use_sim_time', default='True')
この箇所のデフォルトを`False`としたため、シミュレーション上のナビゲーションの実施に`True`が必要となりました。現状の`raspimouse_sim`のREADMEを修正する必要があります。

https://github.com/rt-net/raspimouse_sim/tree/jazzy?tab=readme-ov-file#navigation

2024-11-28 02:31 UTC, KuraZuzu commented
コメントに沿った修正をした上で、実機とシミュレーション上で動作確認を行いました。
実機での動作を確認できましたが、`raspimouse_sim`から実行するシミュレーション上でのナビゲーションの動作を確認できませんでしたが。シミュレーションでは、launchファイルの`use_sim_time`のデフォルトが`True`であることを期待した動作なので、`raspimouse_slam_navigation_ros2`での`use_sim_time`のデフォルトを`True`に戻すか、`raspimouse_sim`側のREADMEを修正する必要があります。

2024-11-28 02:50 UTC, YusukeKato commented
LGTMです！
raspimouse_simのREADMEのコマンドのほうを修正お願いいたします。

2024-11-28 02:50 UTC, merged